---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ipam-haci
  namespace: kube-system
data:
  LOG_LEVEL: debug
  HACI_NETWORK: 10.10.0.0/16
  HACI_URL: ...
  HACI_ROOT: ...
  CONTROLLER_TAG: kubernetes
