---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-ipam-haci
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-ipam-haci
rules:
- apiGroups:
  - ipam.nexinto.com
  resources:
  - ipaddresses
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-ipam-haci
subjects:
- kind: ServiceAccount
  name: k8s-ipam-haci
  namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: k8s-ipam-haci
